spring:
  application:
    name: spring-batch
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
  datasource:
    url: jdbc:mariadb://localhost:3306/spring_batch
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB53Dialect
    show-sql: true
    hibernate:
      ddl-auto: none